name: narraitor
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_fonts: ^4.0.4
  pocketbase: ^0.10.3
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#09090B"
  adaptive_icon_foreground: "assets/logos/logo.png"
  web:
    generate: true
    image_path: "assets/logos/logo.png"
    background_color: "#09090B"
    theme_color: "#09090B"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/welcome-background.png
    - assets/logos/text-logo.png
    - assets/logos/appleDark.png
    - assets/logos/google.png
